CREATE DATABASE EmployeeDB;
USE EmployeeDB;

CREATE TABLE Employees (
    EmpCode INT AUTO_INCREMENT PRIMARY KEY,
    EmpName VARCHAR(50) NOT NULL,
    BasicSalary DECIMAL(10, 2) NOT NULL,
    DA DECIMAL(10, 2) NOT NULL,
    PF DECIMAL(10, 2) NOT NULL,
    NetSalary DECIMAL(10, 2) NOT NULL
);
